name: Build and Publish Helm container

on:
  push:

jobs:

  buildx:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: all
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
    - name: Available platforms
      run: echo Available platforms [${{ steps.buildx.outputs.platforms }}]

    - name: Prepare
      id: prepare
      run: |
        echo ::set-output name=image_repo::${{ secrets.DOCKER_USERNAME }}/k8s-helm
        echo ::set-output name=image_tag::${GITHUB_REF#refs/heads/}
        echo ::set-output name=platforms::linux/amd64,linux/arm64
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: ${{ steps.prepare.outputs.platforms }}
        push: true
        tags: |
          ${{ steps.prepare.outputs.image_repo }}:${{ steps.prepare.outputs.image_tag }}
